import { Property, Candidate, Agent, Appointment } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    agencyId: 'agency-1',
    name: 'Sofia Ribeiro',
    email: 'sofia@domu.pt',
    phone: '+351 912 100 200',
    picture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    specialty: 'Lisboa Centro',
    activeListings: 12,
    conversionRate: 38,
    joinedAt: '2024-03-15',
  },
  {
    id: 'agent-2',
    agencyId: 'agency-1',
    name: 'Miguel Tavares',
    email: 'miguel@domu.pt',
    phone: '+351 913 200 300',
    picture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Miguel',
    specialty: 'Porto e Norte',
    activeListings: 8,
    conversionRate: 42,
    joinedAt: '2024-06-01',
  },
  {
    id: 'agent-3',
    agencyId: 'agency-1',
    name: 'Inês Carvalho',
    email: 'ines@domu.pt',
    phone: '+351 914 300 400',
    picture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ines',
    specialty: 'Cascais e Estoril',
    activeListings: 15,
    conversionRate: 51,
    joinedAt: '2023-11-20',
  },
  {
    id: 'agent-4',
    agencyId: 'agency-1',
    name: 'Rui Mendes',
    email: 'rui@domu.pt',
    phone: '+351 915 400 500',
    picture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rui',
    specialty: 'Algarve',
    activeListings: 6,
    conversionRate: 33,
    joinedAt: '2025-01-10',
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    slug: 't2-campo-ourique-lisboa',
    title: 'T2 Renovado em Campo de Ourique',
    price: 1200,
    description: 'Apartamento T2 completamente renovado, com muita luz natural, localizado numa das zonas mais desejadas de Lisboa. Cozinha equipada, duas casas de banho, varanda com vista para o jardim.',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop',
    ],
    location: 'Campo de Ourique, Lisboa',
    bedrooms: 2,
    bathrooms: 2,
    area: 85,
    sourceUrl: 'https://idealista.pt/example',
    agencyId: 'agency-1',
    agentIds: ['agent-1'],
    criteria: {
      minIncome: 2400, maxPeople: 3, petsAllowed: false,
      advanceMonths: 2, depositMonths: 2, guarantorRequired: true,
      advanceWithoutGuarantor: 4, depositWithoutGuarantor: 3,
    },
    availableSlots: [
      { id: 's1', date: '2026-04-20', time: '10:00', available: true },
      { id: 's2', date: '2026-04-20', time: '14:00', available: true },
      { id: 's3', date: '2026-04-21', time: '11:00', available: true },
    ],
    createdAt: '2026-04-10',
  },
  {
    id: '2',
    slug: 't3-foz-porto',
    title: 'T3 com Vista Mar na Foz do Douro',
    price: 1800,
    description: 'Magnífico T3 com vista mar na prestigiada Foz do Douro. Acabamentos de luxo, suite com closet, sala ampla com lareira.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
    ],
    location: 'Foz do Douro, Porto',
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    sourceUrl: 'https://idealista.pt/example2',
    agencyId: 'agency-1',
    agentIds: ['agent-2', 'agent-3'],
    criteria: {
      minIncome: 3600, maxPeople: 5, petsAllowed: true,
      advanceMonths: 2, depositMonths: 2, guarantorRequired: true,
      advanceWithoutGuarantor: 3, depositWithoutGuarantor: 3,
    },
    availableSlots: [
      { id: 's5', date: '2026-04-21', time: '09:00', available: true },
      { id: 's6', date: '2026-04-21', time: '15:00', available: true },
    ],
    createdAt: '2026-04-12',
  },
  {
    id: '3',
    slug: 'villa-cascais',
    title: 'Villa de Luxo em Cascais',
    price: 4500,
    description: 'Villa contemporânea com piscina infinita, jardim privado e vista mar. Acabamentos premium.',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop',
    ],
    location: 'Cascais',
    bedrooms: 4,
    bathrooms: 4,
    area: 280,
    sourceUrl: 'https://idealista.pt/example3',
    agencyId: 'agency-1',
    agentIds: ['agent-3'],
    criteria: {
      minIncome: 9000, maxPeople: 6, petsAllowed: true,
      advanceMonths: 3, depositMonths: 3, guarantorRequired: false,
    },
    availableSlots: [],
    createdAt: '2026-04-14',
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: 'c1', propertyId: '1', name: 'Maria Silva', email: 'maria@example.com', phone: '+351 912 345 678',
    monthlyIncome: 3500, numberOfPeople: 2, hasPets: false, hasGuarantor: true,
    employmentType: 'permanent', employmentDuration: 48, score: 92, classification: 'excellent',
    status: 'visit_scheduled', scheduledVisit: '2026-04-20T10:00', createdAt: '2026-04-11',
  },
  {
    id: 'c2', propertyId: '1', name: 'João Santos', email: 'joao@example.com', phone: '+351 923 456 789',
    monthlyIncome: 2800, numberOfPeople: 1, hasPets: false, hasGuarantor: true,
    employmentType: 'permanent', employmentDuration: 24, score: 85, classification: 'excellent',
    status: 'approved', createdAt: '2026-04-12',
  },
  {
    id: 'c3', propertyId: '1', name: 'Ana Costa', email: 'ana@example.com', phone: '+351 934 567 890',
    monthlyIncome: 2000, numberOfPeople: 2, hasPets: true, petDetails: '1 gato', hasGuarantor: false,
    employmentType: 'contract', employmentDuration: 12, score: 35, classification: 'low',
    status: 'new', createdAt: '2026-04-13',
  },
  {
    id: 'c4', propertyId: '1', name: 'Pedro Martins', email: 'pedro@example.com', phone: '+351 945 678 901',
    monthlyIncome: 2600, numberOfPeople: 3, hasPets: false, hasGuarantor: true,
    employmentType: 'freelancer', employmentDuration: 36, score: 58, classification: 'potential',
    status: 'new', createdAt: '2026-04-14',
  },
  {
    id: 'c5', propertyId: '2', name: 'Carla Nunes', email: 'carla@example.com', phone: '+351 961 111 222',
    monthlyIncome: 5200, numberOfPeople: 3, hasPets: true, petDetails: 'cão pequeno', hasGuarantor: true,
    employmentType: 'permanent', employmentDuration: 60, score: 88, classification: 'excellent',
    status: 'visit_scheduled', scheduledVisit: '2026-04-21T09:00', createdAt: '2026-04-13',
  },
  {
    id: 'c6', propertyId: '3', name: 'Henrique Lopes', email: 'henrique@example.com', phone: '+351 962 333 444',
    monthlyIncome: 14000, numberOfPeople: 4, hasPets: true, hasGuarantor: false,
    employmentType: 'permanent', employmentDuration: 96, score: 90, classification: 'excellent',
    status: 'visit_scheduled', scheduledVisit: '2026-04-22T16:00', createdAt: '2026-04-14',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1', propertyId: '1', candidateId: 'c1', agentId: 'agent-1',
    date: '2026-04-20', time: '10:00', status: 'confirmed',
    notes: 'Candidato muito interessado, trazer contrato.',
  },
  {
    id: 'apt-2', propertyId: '2', candidateId: 'c5', agentId: 'agent-2',
    date: '2026-04-21', time: '09:00', status: 'confirmed',
  },
  {
    id: 'apt-3', propertyId: '3', candidateId: 'c6', agentId: 'agent-3',
    date: '2026-04-22', time: '16:00', status: 'confirmed',
    notes: 'Visita guiada incluindo área externa e piscina.',
  },
  {
    id: 'apt-4', propertyId: '1', candidateId: 'c2', agentId: 'agent-1',
    date: '2026-04-18', time: '14:00', status: 'completed',
  },
];
