import { Property, Candidate } from './types';

export const mockProperties: Property[] = [
  {
    id: '1',
    slug: 't2-campo-ourique-lisboa',
    title: 'T2 Renovado em Campo de Ourique',
    price: 1200,
    description: 'Apartamento T2 completamente renovado, com muita luz natural, localizado numa das zonas mais desejadas de Lisboa. Cozinha equipada, duas casas de banho, varanda com vista para o jardim. A poucos minutos do Jardim da Estrela e com excelentes acessos de transportes.',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop',
    ],
    location: 'Campo de Ourique, Lisboa',
    bedrooms: 2,
    bathrooms: 2,
    area: 85,
    sourceUrl: 'https://idealista.pt/example',
    agencyId: 'agency-1',
    criteria: {
      minIncome: 2400,
      maxPeople: 3,
      petsAllowed: false,
      advanceMonths: 2,
      depositMonths: 2,
      guarantorRequired: true,
      advanceWithoutGuarantor: 4,
      depositWithoutGuarantor: 3,
    },
    availableSlots: [
      { id: 's1', date: '2026-04-20', time: '10:00', available: true },
      { id: 's2', date: '2026-04-20', time: '14:00', available: true },
      { id: 's3', date: '2026-04-21', time: '11:00', available: true },
      { id: 's4', date: '2026-04-22', time: '16:00', available: true },
    ],
    createdAt: '2026-04-10',
  },
  {
    id: '2',
    slug: 't3-foz-porto',
    title: 'T3 com Vista Mar na Foz do Douro',
    price: 1800,
    description: 'Magnífico T3 com vista mar na prestigiada Foz do Douro. Acabamentos de luxo, suite com closet, sala ampla com lareira. Garagem para dois carros. Condomínio fechado com jardim e piscina.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
    ],
    location: 'Foz do Douro, Porto',
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    sourceUrl: 'https://idealista.pt/example2',
    agencyId: 'agency-1',
    criteria: {
      minIncome: 3600,
      maxPeople: 5,
      petsAllowed: true,
      advanceMonths: 2,
      depositMonths: 2,
      guarantorRequired: true,
      advanceWithoutGuarantor: 3,
      depositWithoutGuarantor: 3,
    },
    availableSlots: [
      { id: 's5', date: '2026-04-21', time: '09:00', available: true },
      { id: 's6', date: '2026-04-21', time: '15:00', available: true },
    ],
    createdAt: '2026-04-12',
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: 'c1',
    propertyId: '1',
    name: 'Maria Silva',
    email: 'maria@example.com',
    phone: '+351 912 345 678',
    monthlyIncome: 3500,
    numberOfPeople: 2,
    hasPets: false,
    hasGuarantor: true,
    employmentType: 'permanent',
    employmentDuration: 48,
    score: 92,
    classification: 'excellent',
    status: 'visit_scheduled',
    scheduledVisit: '2026-04-20T10:00',
    createdAt: '2026-04-11',
  },
  {
    id: 'c2',
    propertyId: '1',
    name: 'João Santos',
    email: 'joao@example.com',
    phone: '+351 923 456 789',
    monthlyIncome: 2800,
    numberOfPeople: 1,
    hasPets: false,
    hasGuarantor: true,
    employmentType: 'permanent',
    employmentDuration: 24,
    score: 85,
    classification: 'excellent',
    status: 'approved',
    createdAt: '2026-04-12',
  },
  {
    id: 'c3',
    propertyId: '1',
    name: 'Ana Costa',
    email: 'ana@example.com',
    phone: '+351 934 567 890',
    monthlyIncome: 2000,
    numberOfPeople: 2,
    hasPets: true,
    petDetails: '1 gato',
    hasGuarantor: false,
    employmentType: 'contract',
    employmentDuration: 12,
    score: 35,
    classification: 'low',
    status: 'new',
    createdAt: '2026-04-13',
  },
  {
    id: 'c4',
    propertyId: '1',
    name: 'Pedro Martins',
    email: 'pedro@example.com',
    phone: '+351 945 678 901',
    monthlyIncome: 2600,
    numberOfPeople: 3,
    hasPets: false,
    hasGuarantor: true,
    employmentType: 'freelancer',
    employmentDuration: 36,
    score: 58,
    classification: 'potential',
    status: 'new',
    createdAt: '2026-04-14',
  },
];
